/* Generated By:JavaCC: Do not edit this line. ECConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ECConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 1;
  /** RegularExpression Id. */
  int FIN = 2;
  /** RegularExpression Id. */
  int COMA = 3;
  /** RegularExpression Id. */
  int FUNCION = 4;
  /** RegularExpression Id. */
  int FIN_FUNCION = 5;
  /** RegularExpression Id. */
  int RETORNAR = 6;
  /** RegularExpression Id. */
  int ENTERO = 7;
  /** RegularExpression Id. */
  int FLOTANTE = 8;
  /** RegularExpression Id. */
  int CADENA = 9;
  /** RegularExpression Id. */
  int CARACTER = 10;
  /** RegularExpression Id. */
  int BOOLEANO = 11;
  /** RegularExpression Id. */
  int INTERPRETAR = 12;
  /** RegularExpression Id. */
  int ESCRIBIR = 13;
  /** RegularExpression Id. */
  int ESTABLECER = 14;
  /** RegularExpression Id. */
  int ASIGNACION = 15;
  /** RegularExpression Id. */
  int SUMA = 16;
  /** RegularExpression Id. */
  int RESTA = 17;
  /** RegularExpression Id. */
  int MULTIPLICACION = 18;
  /** RegularExpression Id. */
  int DIVISION = 19;
  /** RegularExpression Id. */
  int MODULO = 20;
  /** RegularExpression Id. */
  int LOGICO_AND = 21;
  /** RegularExpression Id. */
  int LOGICO_OR = 22;
  /** RegularExpression Id. */
  int LOGICO_NOT = 23;
  /** RegularExpression Id. */
  int OPERADOR_IGUAL = 24;
  /** RegularExpression Id. */
  int OPERADOR_DIFERENTE = 25;
  /** RegularExpression Id. */
  int OPERADOR_MAYOR = 26;
  /** RegularExpression Id. */
  int OPERADOR_MENOR = 27;
  /** RegularExpression Id. */
  int OPERADOR_MAYOR_IGUAL = 28;
  /** RegularExpression Id. */
  int OPERADOR_MENOR_IGUAL = 29;
  /** RegularExpression Id. */
  int OPERADOR_DOS_PUNTOS = 30;
  /** RegularExpression Id. */
  int PAREN_ABIERTO = 31;
  /** RegularExpression Id. */
  int PAREN_CERRADO = 32;
  /** RegularExpression Id. */
  int INDICE_ABIERTO = 33;
  /** RegularExpression Id. */
  int INDICE_CERRADO = 34;
  /** RegularExpression Id. */
  int LETRA = 35;
  /** RegularExpression Id. */
  int NUMERO = 36;
  /** RegularExpression Id. */
  int CADENA_TEXTO = 37;
  /** RegularExpression Id. */
  int CARACTER_TEXTO = 38;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 39;
  /** RegularExpression Id. */
  int NUMERO_DECIMAL = 40;
  /** RegularExpression Id. */
  int BOOLEANO_FALSO = 41;
  /** RegularExpression Id. */
  int BOOLEANO_VERDADERO = 42;
  /** RegularExpression Id. */
  int DELIMITADOR = 43;
  /** RegularExpression Id. */
  int INICIO_CICLO_PARA = 44;
  /** RegularExpression Id. */
  int CONDICION_CICLO_PARA = 45;
  /** RegularExpression Id. */
  int INCREMENTO_CICLO_PARA = 46;
  /** RegularExpression Id. */
  int FIN_CICLO_PARA = 47;
  /** RegularExpression Id. */
  int INICIO_CICLO_MIENTRAS = 48;
  /** RegularExpression Id. */
  int FIN_CICLO_MIENTRAS = 49;
  /** RegularExpression Id. */
  int INICIO_CICLO_REPETIR = 50;
  /** RegularExpression Id. */
  int CONDICION_CICLO_REPETIR = 51;
  /** RegularExpression Id. */
  int INICIO_CONDICIONAL_SI = 52;
  /** RegularExpression Id. */
  int ENTONCES = 53;
  /** RegularExpression Id. */
  int CONDICIONAL_SINO = 54;
  /** RegularExpression Id. */
  int FIN_CONDICIONAL_SI = 55;
  /** RegularExpression Id. */
  int INICIO_CONDICIONAL_CONFORME = 56;
  /** RegularExpression Id. */
  int CASO = 57;
  /** RegularExpression Id. */
  int CASO_PREDETERMINADO = 58;
  /** RegularExpression Id. */
  int FIN_CONFORME = 59;
  /** RegularExpression Id. */
  int HACER = 60;
  /** RegularExpression Id. */
  int VARIABLE = 61;
  /** RegularExpression Id. */
  int COMENTARIO = 66;
  /** RegularExpression Id. */
  int NUMERO_INVALIDO = 67;
  /** RegularExpression Id. */
  int INVALIDO = 68;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Inicio\"",
    "\"Fin\"",
    "\",\"",
    "\"Funcion\"",
    "\"FinFuncion\"",
    "\"Retornar\"",
    "<ENTERO>",
    "<FLOTANTE>",
    "<CADENA>",
    "<CARACTER>",
    "<BOOLEANO>",
    "\"Interpretar\"",
    "\"Escribir\"",
    "\"Establecer\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<LETRA>",
    "<NUMERO>",
    "<CADENA_TEXTO>",
    "<CARACTER_TEXTO>",
    "<NUMERO_ENTERO>",
    "<NUMERO_DECIMAL>",
    "\"Falso\"",
    "\"Verdadero\"",
    "\";\"",
    "\"Para\"",
    "\"Hasta que\"",
    "\"Con incremento\"",
    "\"FinPara\"",
    "\"Mientras\"",
    "\"FinMientras\"",
    "\"Repetir\"",
    "\"Finaliza cuando\"",
    "\"Si\"",
    "\"Entonces\"",
    "\"Sino\"",
    "\"FinSi\"",
    "\"Conforme\"",
    "\"Caso\"",
    "\"En otro caso\"",
    "\"FinConforme\"",
    "\"Hacer\"",
    "<VARIABLE>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "<COMENTARIO>",
    "<NUMERO_INVALIDO>",
    "<INVALIDO>",
  };

}
